---

controller_templates:

  - name: "LINUX / Register with Insights"
    job_type: run
    inventory: "Demo Inventory"
    project: "Ansible Product Demos"
    playbook: "linux/ec2_register.yml"
    notification_templates_started: Telemetry
    notification_templates_success: Telemetry
    notification_templates_error: Telemetry
    credentials:
      - "Demo Credential"
    survey_enabled: true
    extra_vars:
      activation_key: !unsafe "RHEL{{ ansible_distribution_major_version }}_{{ env }}"
      org_id: REPLACEME
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true
        - question_name: Choose Environment
          type: multiplechoice
          variable: env
          choices:
            - Dev
            - QA
            - Prod
          required: true
        - question_name: Ansible Inventory Group (and Insights tag) to be created
          type: text
          variable: insights_tag
          required: true
        - question_name: Org ID
          type: text
          variable: org_id
          required: true